# Generated by Django 6.0.4 on 2026-05-17 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0005_alter_raffle_slug'),
        ('sales', '0002_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ticket',
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sale',
            name='raffle',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='raffle',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador_nome', models.CharField(max_length=255)),
                ('comprador_email', models.EmailField(max_length=254)),
                ('comprador_telefone', models.CharField(max_length=30)),
                ('comprador_cpf', models.CharField(max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprovante_url', models.URLField(blank=True, null=True)),
                ('data_expiracao', models.DateTimeField()),
                ('status', models.CharField(choices=[('reservada', 'Reservada'), ('aguardando', 'Aguardando'), ('paga', 'Paga'), ('expirada', 'Expirada'), ('rejeitada', 'Rejeitada')], default='reservada', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='raffles.raffle')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.numerorifa')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sales.transaction')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
