# Generated by Django 6.0.4 on 2026-05-23 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0005_alter_raffle_slug'),
        ('sales', '0003_remove_orderitem_order_remove_orderitem_ticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='rifa',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='transacao',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='organizador',
        ),
        migrations.AddField(
            model_name='transaction',
            name='raffle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='raffles.raffle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedorrifa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comprador_cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comprador_telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='comissao_fixa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendedorrifa',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.raffle'),
        ),
        migrations.AlterField(
            model_name='vendedorrifa',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.vendedor'),
        ),
    ]
