# Generated by Django 6.0.4 on 2026-05-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_criado_em_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('reservada', 'Reservada'), ('aguardando', 'Aguardando'), ('paga', 'Paga'), ('expirada', 'Expirada'), ('rejeitada', 'Rejeitada')], default='reservada', max_length=30),
        ),
    ]
