# Generated by Django 6.0.4 on 2026-06-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_transaction_comprovante_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('reservada', 'Reservada'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('paga', 'Paga'), ('expirada', 'Expirada'), ('rejeitada', 'Rejeitada')], default='reservada', max_length=30),
        ),
    ]
