# Generated by Django 6.0.4 on 2026-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
