# Generated by Django 6.0.4 on 2026-06-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_transaction_motivo_rejeicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='total_vendas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
