# Generated by Django 6.0.4 on 2026-04-25 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('descricao_html', models.TextField(blank=True, null=True)),
                ('valor_numero', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_numeros', models.PositiveIntegerField()),
                ('data_sorteio', models.DateTimeField()),
                ('chave_pix', models.CharField(max_length=255)),
                ('tempo_reserva', models.PositiveIntegerField(help_text='Tempo em minutos')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('closed', 'Encerrada')], default='draft', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('link_transmissao', models.URLField(blank=True, null=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='raffles/main/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='raffles/prizes/')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='raffles.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='RaffleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='raffles/gallery/')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='raffles.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponivel', max_length=15)),
                ('reservado_em', models.DateTimeField(blank=True, null=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='raffles.raffle')),
            ],
            options={
                'unique_together': {('rifa', 'numero')},
            },
        ),
    ]
