# Generated by Django 4.2.29 on 2026-04-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_numbers', models.IntegerField()),
                ('price_per_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('draw_date', models.DateTimeField()),
                ('live_stream_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
        ),
    ]
