# Generated by Django 6.0.4 on 2026-04-25 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['posicao']},
        ),
        migrations.AlterUniqueTogether(
            name='numerorifa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='raffleimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='numerorifa',
            constraint=models.UniqueConstraint(fields=('rifa', 'numero'), name='unique_rifa_numero'),
        ),
        migrations.AddConstraint(
            model_name='prize',
            constraint=models.UniqueConstraint(fields=('rifa', 'posicao'), name='unique_prize_position_per_raffle'),
        ),
    ]
