# Generated by Django 6.0.4 on 2026-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_alter_prize_options_alter_numerorifa_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerorifa',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('pago', 'Pago')], default='disponivel', max_length=30),
        ),
    ]
