# Generated by Django 6.0.4 on 2026-05-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0003_alter_numerorifa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
