# Generated by Django 6.0.4 on 2026-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_raffle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
