# Generated by Django 6.0.4 on 2026-06-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0005_alter_raffle_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoSorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador_nome', models.CharField(max_length=255)),
                ('data_sorteio', models.DateTimeField(auto_now_add=True)),
                ('numero_sorteado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.numerorifa')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.prize')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='raffles.raffle')),
            ],
        ),
    ]
