# Generated by Django 6.0.3 on 2026-04-01 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('raffles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.raffle'),
        ),
    ]
