# Generated by Django 6.0.4 on 2026-04-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('organizador', 'Organizador'), ('vendedor', 'Vendedor')], default='organizador', max_length=20),
        ),
    ]
