# Generated by Django 6.0.4 on 2026-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_phone_user_telefone_user_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_vendas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
